<a href="https://colab.research.google.com/github/Jack-Cruz/Procesamiento_imagen/blob/main/notebook/Clase_03_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a = [1, 2, 3, 4, 5, 6]

In [2]:
def get(i):
  return a[i]

In [3]:
get(3)

4

In [4]:
rows = 2
cols = 3

In [6]:
def get2(i, j):
  return a[i*cols + j]

In [7]:
get2(1, 2)

6

In [8]:
import numpy as np

In [9]:
A = np.array(a)

In [10]:
A

array([1, 2, 3, 4, 5, 6])

In [11]:
A.shape

(6,)

In [12]:
A[1, 2]

IndexError: ignored

In [13]:
A = A.reshape((2, 3))

In [14]:
A[1, 2]

6

In [15]:
A.shape

(2, 3)

In [16]:
B = A.reshape((2, 3, 1, 1, 1, 1, 1))

In [17]:
B.shape

(2, 3, 1, 1, 1, 1, 1)

In [20]:
B[1, 2]

array([[[[[6]]]]])

In [21]:
B[1, 2].shape

(1, 1, 1, 1, 1)

In [22]:
soyunatupla = (1, 2, 3, 4)

In [23]:
print(soyunatupla[0])
print(soyunatupla[1])
print(soyunatupla[2])
print(soyunatupla[3])

1
2
3
4


In [24]:
soyunatupla[1] = 100

TypeError: ignored

In [25]:
C = B[1, 2]

In [26]:
C[0, 0, 0, 0]

array([6])

In [27]:
C[0, 0, 0, 0, 0]

6

In [28]:
C[0, 0, 0, 0, 0] = 100

In [31]:
B

array([[[[[[[  1]]]]],




        [[[[[  2]]]]],




        [[[[[  3]]]]]],





       [[[[[[  4]]]]],




        [[[[[  5]]]]],




        [[[[[100]]]]]]])

In [32]:
A

array([[  1,   2,   3],
       [  4,   5, 100]])

In [33]:
b = [[1, 2, 3], [4, 5, 6]]

In [35]:
b[1][2]

6

In [36]:
b[1, 2]

TypeError: ignored

In [37]:
B[1, 2]

array([[[[[100]]]]])